import colorama,time
from colorama import *

def wi():

	ui = input(Fore.YELLOW+"Enter wifi name: ")
	if(ui == "B.N.D"):
		time.sleep(1)
		print(Fore.GREEN+f"Finding Wifi named {ui} ")
		time.sleep(2.5)
		print("Locating Connection!..")
		time.sleep(5)
		print("Authenticating wifi named: "+ui)
		time.sleep(5)
		for i in range(50):
			print("Sending Deauth packets ==> "+ui)
			time.sleep(.4)
		print("Wifi Handshake captured!")
		time.sleep(25)
		print("Checking connection! ..")
		time.sleep(7)
		print("Cracking...")
		time.sleep(25)
		print(Fore.YELLOW+"Connection "+ui+" Establish!")
		time.sleep(1.5)
		print(f"wifi {ui} password found: '7894561230'")
		print("\nHacking Complete!\n")
		
	elif(ui == 'Avengers'):
		time.sleep(1)
		print(Fore.GREEN+f"Finding Wifi named {ui} ")
		time.sleep(2.5)
		print("Locating Connection!..")
		time.sleep(5)
		print("Authenticating wifi named: "+ui)
		time.sleep(5)
		for i in range(50):
			print("Sending Deauth packets ==> "+ui)
			time.sleep(.4)
		print("Wifi Handshake captured!")
		time.sleep(25)
		print("Checking connection! ..")
		time.sleep(7)
		print("Cracking...")
		time.sleep(25)
		print(Fore.YELLOW+"Connection "+ui+" Establish!")
		time.sleep(1.5)
		print(f"wifi {ui} password found: 'mamaels1938'")
		print("\nHacking Complete!\n")
	
	elif(ui == "FBI"):
		time.sleep(1)
		print(Fore.GREEN+f"Finding Wifi named {ui} ")
		time.sleep(2.5)
		print("Locating Connection!..")
		time.sleep(5)
		print("Authenticating wifi named: "+ui)
		time.sleep(5)
		for i in range(50):
			print("Sending Deauth packets ==> "+ui)
			time.sleep(.4)
		print("Wifi Handshake captured!")
		time.sleep(25)
		print("Checking connection! ..")
		time.sleep(7)
		print("Cracking...")
		time.sleep(25)
		print(Fore.RED+"Connection "+ui+" Establish!")
		time.sleep(1.5)
		print(f"wifi {ui} password HASHfound: 'b0de906040b79f433a8d374e11029e43'")
		print("\nHacking Finish!\n")
		
	elif(ui == "C.I.A"):
		time.sleep(1)
		print(Fore.GREEN+f"Finding Wifi named {ui} ")
		time.sleep(2.5)
		print("Locating Connection!..")
		time.sleep(5)
		print("Authenticating wifi named: "+ui)
		time.sleep(5)
		for i in range(50):
			print("Sending Deauth packets ==> "+ui)
			time.sleep(.4)
		print("Wifi Handshake captured!")
		time.sleep(26)
		print("Checking connection! ..")
		time.sleep(7)
		print("Cracking...")
		time.sleep(25)
		print(Fore.RED+"Connection "+ui+" Establish!")
		time.sleep(1.5)
		print(f"wifi {ui} password-HASHfound: 'b0de906040b79f433a8d374e11029e43'")
		print("\nHacking Finish!\n")
		
	else:	
		time.sleep(1)
		print(Fore.GREEN+f"Finding Wifi named {ui} ")
		time.sleep(2.5)
		print("Locating Connection!..")
		time.sleep(5)
		print("Authenticating wifi named: "+ui)
		time.sleep(5)
		for i in range(100):
			print("Sending Deauth packets ==> "+ui)
			time.sleep(.4)
		print("Wifi Handshake captured!")
		time.sleep(25)
		print("Checking connection! ..")
		time.sleep(7)
		print("Cracking...")
		time.sleep(25)
		print(Fore.RED+"Error! Connection "+ui+" Cannot Establish!")
		time.sleep(1.5)
		print("Wifi "+ui+" Hack Failed!")
	
		print("\nNo Wifi Connection Found!")
		print("Try again! make sure your spelling is correct!\n")
		
		
